# Functions
- list comprehences
- maps
- lambda
- filters
- reduce

In [5]:
s=input()
p=['!','@','#','$','%']

for i s:
    if i.isdigit:
        print("not valid")
    else:
        if i.isalpha
    

sai@
jfjf


In [8]:
s=int(input())
def fact(p):
    if(p==0 or p==1):
        return 1
    else:
        return p*fact(p-1)
sp=[fact(i) for i in range(1,s+1)]
print(sp)

5
[1, 2, 6, 24, 120]


In [15]:
s=int(input())
def cum(q):
    p=0
    for i in range(1,q+1):
        p=p+i
    return p
l=[cum(i) for i in range(1,s+1)]
print(l)

11
[1, 3, 6, 10, 15, 21, 28, 36, 45, 55, 66]


In [ ]:
s=int(input())
def leap(p):
    if((p%4==0 and p%100!=0) or p%400==0):
        return p
l=[leap(i) for i in range(1,s+1)]
print(l)

In [5]:
s=int(input())
l=[p for p in range(1,s+1) if p%2==0]
print(l)

4
[2, 4]


In [6]:
s=int(input())
l=[p for p in range(1,s+1) if p%2!=0]
print(l)

5
[1, 3, 5]


In [32]:
s=int(input())
p=0
while(p/s<=0.16):
    p+=2
print(round((p/s)*100))

10
20


In [17]:
def hmm(p):
    return(p**2)
s=[1,2,3,4]
si=set(map(hmm,s))
print(si)

{16, 1, 4, 9}


In [25]:
2/12




0.16666666666666666

In [17]:
# Filtering
# syntax:
# filter(functionname,sequence)
def eligible(a):
    if a>=18:
        return True
l=[1,2,34,45,6]
print(list(filter(eligible,l)))

[34, 45]


In [21]:
def vow(p):
    w=['a','e','i','o','u']
    if p in w:
        return True
s=["j","h","g","i","g"]
print(list(filter(vow,s)))

['i']


In [40]:
def div(p):
     if((p%3==0) and (p%5==0)):
            return True
       
s=[1,2,34,90,45,60,6,9,10]
q=(list(filter(div,s)))
q.sort()
print(q)

[45, 60, 90]


In [57]:
from functools import reduce
def add(x,y):
    return x+y
s=int(input())
print(reduce(add,range(1,s+1)))

7
28


In [1]:
s=input()
l=[i for i in s]
print(l)

im pradeep
['i', 'm', ' ', 'p', 'r', 'a', 'd', 'e', 'e', 'p']


In [10]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [19]:
import numpy as np
a=np.array([[[1,2,3],[4,5,6],[5,6,7]]])
print(a)

[[[1 2 3]
  [4 5 6]
  [5 6 7]]]


In [16]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}

In [28]:
import numpy as np
b=np.arange(15).reshape(3,5)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [5]:
import numpy as p
s=p.arange(25).reshape(5,5)
print(s)
q=p.array([s[1,3],s[1,4]],[s[2,3],s[2,4]])
print(q)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


TypeError: data type not understood

In [8]:
print([s[1,3],s[2,4]])

[8, 14]


In [15]:
s[1::1,3::1]

array([[ 8,  9],
       [13, 14],
       [18, 19],
       [23, 24]])